# Numpy ndarrays

In [1]:
import numpy as np

In [2]:
# Create a sequential integer list and a Numpy NDArray of the same, for comparisons:

a_list = list(range(10000000))
b =  np.arange(10000000)

In [3]:
a_list[0:9]

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [4]:
b[0:9]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

How do we multiply every value by two in standard Python lists?

In [5]:
def double():
    for i in range(len(a_list)):
        a_list[i] *= 2
        
double()
a_list[0:9]

[0, 2, 4, 6, 8, 10, 12, 14, 16]

## Code Review
Is anything wrong with the double() function above?

In [6]:
%timeit double()   # find out how fast this operation is

1.05 s ± 45 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [7]:
a_list[0:9]

[0, 512, 1024, 1536, 2048, 2560, 3072, 3584, 4096]

What went wrong with the data in the list above?


## Vectorized computations
The main reason to use Numpy is that most operations on matrices can be done in "vectorized" fashion.  That means we usually don't need to write loops to go through values in arrays/matrices, and operations will be implicity looped and performed by pre-compiled C code that is much faster.

In [8]:
# Attempt a vectorized calculation on a list
[0, 10, 3] * 2


[0, 10, 3, 0, 10, 3]

In [9]:
b * 2

array([       0,        2,        4, ..., 19999994, 19999996, 19999998])

In [10]:
# This is how to double every value in the b array using a vectorized multiplication operation:
%time b *= 2

CPU times: user 8.65 ms, sys: 1.03 ms, total: 9.68 ms
Wall time: 8.16 ms


In [11]:
b[0:9]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

In [12]:
b[::3] = 0
b[0:30]

array([ 0,  2,  4,  0,  8, 10,  0, 14, 16,  0, 20, 22,  0, 26, 28,  0, 32,
       34,  0, 38, 40,  0, 44, 46,  0, 50, 52,  0, 56, 58])

## Slices of ndarrays are "views" into the same object.
This is very different than how lists behave.  Let's explore the difference.

In [13]:
a_slice = a_list[0:9]

In [14]:
a_slice

[0, 512, 1024, 1536, 2048, 2560, 3072, 3584, 4096]

In [15]:
a_slice[3] = 99
a_slice

[0, 512, 1024, 99, 2048, 2560, 3072, 3584, 4096]

Notice below that after we mutated the slice of the list "a_list", the list itself did *not* get changed.  That's because assigning the *slice* of a list to another variable creates a *copy*.

In [16]:
a_list[0:9]

[0, 512, 1024, 1536, 2048, 2560, 3072, 3584, 4096]

Now we'll try the exact same sequence of steps with an ndarray.

In [17]:
b[0:9]   # display the ndarray's first few values

array([ 0,  2,  4,  0,  8, 10,  0, 14, 16])

In [18]:
b_slice = b[0:9]   # assign an ndarray's slice to a new variable, analogous to what we did above with a list.

In [19]:
b_slice

array([ 0,  2,  4,  0,  8, 10,  0, 14, 16])

In [20]:
b_slice[3] = 99   # now modify an element within that slice.
b_slice

array([ 0,  2,  4, 99,  8, 10,  0, 14, 16])

Last, we peek again at the original ndarray's values.  It also changed!  This is the purpose and effect of "views" in ndarrays.  Why would the designers want this behavior?

In [21]:
b[0:9]

array([ 0,  2,  4, 99,  8, 10,  0, 14, 16])

In [22]:
type(b[0])

numpy.int64

## Experiments with using numpy with a character grid:

In [23]:
lines = ['appled',
         'nnigal',
         'dogsbe',
         'rshrei',
         'oxenyy',
         'ilwepq',
         'drehsm']

# method of "loading" these characters into array adapted from example at
# https://stackoverflow.com/questions/9476797/how-do-i-create-character-arrays-in-numpy

g = np.array(lines, dtype=np.unicode_)
grid = g.view('U1').reshape((g.size, -1))
print(grid)

[['a' 'p' 'p' 'l' 'e' 'd']
 ['n' 'n' 'i' 'g' 'a' 'l']
 ['d' 'o' 'g' 's' 'b' 'e']
 ['r' 's' 'h' 'r' 'e' 'i']
 ['o' 'x' 'e' 'n' 'y' 'y']
 ['i' 'l' 'w' 'e' 'p' 'q']
 ['d' 'r' 'e' 'h' 's' 'm']]


In [24]:
grid.shape  # Verify the dimensions of this array: (7 rows by 6 columns)

(7, 6)

# Extracting columns
When we have a list of lists, or similar 2-dimensional structures, we often need to extract something from COLUMNS. In regular Python structures such as a list of lists, this requires looping to do:

In [25]:
# This kind of syntax does NOT work for lists:

# lines[][0]
# or 
# lines[:, 0]

In [26]:
lines

['appled', 'nnigal', 'dogsbe', 'rshrei', 'oxenyy', 'ilwepq', 'drehsm']

In [27]:
lines[0:2][0]

'appled'

In [28]:
column_0 = []
for line in lines:
    column_0.append(line[0])
print(column_0)

['a', 'n', 'd', 'r', 'o', 'i', 'd']


## ndarray columns are better:
With Numpy ndarrays, our slicing features work MULTI-dimensionally.  
So we can extract a column easily (and very fast) like this:

In [29]:
print(grid[:, 0])  # vertical slice

['a' 'n' 'd' 'r' 'o' 'i' 'd']


In [30]:
print(grid[2:, 0])  

['d' 'r' 'o' 'i' 'd']


In [31]:
# Numpy arrays are iterable. 
# So we can use string join to convert array into a single string:
'*'.join(grid[:, 0])  

'a*n*d*r*o*i*d'

In [32]:
''.join(grid[0, 0:5])  # with 2D slicing, pick 'apple' from the grid.

'apple'

# Searching a 2D array

In [33]:
# one way to search for a specific value in a specific row:
if ['e'] in grid[0]:
    print('found an e.')

found an e.


In [34]:
grid[0]

array(['a', 'p', 'p', 'l', 'e', 'd'], dtype='<U1')

In [35]:
# This approach DOES NOT WORK to search for a sequence:
if ['a', 'p', 'p', 'l', 'e'] in list(grid[0]):
    print('found an apple.')
else:
    print("can't find the apple!")

can't find the apple!


In [36]:
# So why does this similar example work in lists??
x = [ ['a', 'p', 'p', 'l', 'e'],
      ['p', 'o', 't','a','t','o']]
if ['a', 'p', 'p', 'l', 'e'] in x:
    print('found an apple.')


found an apple.


This next approach does work to find strings within a row or column, but for large grids it would likely be slow, because we're losing most efficiency advantages of the ndarray.  Imagine if this grid contained 1000 rows and columns:

In [37]:
for row in range(grid.shape[0]):
    if 'oxen' in ''.join(grid[row]):
        print('found the oxen in row', row)

found the oxen in row 4


A different idea is to use the filtering features of ndarray to eliminate the rows that can't contain our search target.  In English vocabulary, the "x" in "oxen" is rare, so let's try filtering for "x":

In [38]:
grid

array([['a', 'p', 'p', 'l', 'e', 'd'],
       ['n', 'n', 'i', 'g', 'a', 'l'],
       ['d', 'o', 'g', 's', 'b', 'e'],
       ['r', 's', 'h', 'r', 'e', 'i'],
       ['o', 'x', 'e', 'n', 'y', 'y'],
       ['i', 'l', 'w', 'e', 'p', 'q'],
       ['d', 'r', 'e', 'h', 's', 'm']], dtype='<U1')

In [39]:
grid == 'x'  # builds a matching ndarray of True/False on the condition

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False,  True, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [40]:
np.where(grid == 'x', grid, '') # Use the condition to extract all "x" values

array([['', '', '', '', '', ''],
       ['', '', '', '', '', ''],
       ['', '', '', '', '', ''],
       ['', '', '', '', '', ''],
       ['', 'x', '', '', '', ''],
       ['', '', '', '', '', ''],
       ['', '', '', '', '', '']], dtype='<U1')

From the above result, we know that if "oxen" exists in the grid at all, it must be located through index position 4,1.

# Clever counting
The numpy.count_nonzero() method works on True/False values! This is because like most other languages, zeros are considered False, and most other values are considered True.  

In [41]:
# See which columns have an 'x' value:
np.count_nonzero(grid == 'x', axis=0)

array([0, 1, 0, 0, 0, 0])

In [42]:
# See which rows have an 'x' value:
np.count_nonzero(grid == 'x', axis=1)

array([0, 0, 0, 0, 1, 0, 0])

In [43]:
columns = np.count_nonzero(grid == 'x', axis=0)
rows    = np.count_nonzero(grid == 'x', axis=1)

possible_columns = np.where(columns, grid, '')
print(possible_columns)
print()
possible_rows = np.transpose(np.where(rows, np.transpose(grid), ''))
print(possible_rows)

[['' 'p' '' '' '' '']
 ['' 'n' '' '' '' '']
 ['' 'o' '' '' '' '']
 ['' 's' '' '' '' '']
 ['' 'x' '' '' '' '']
 ['' 'l' '' '' '' '']
 ['' 'r' '' '' '' '']]

[['' '' '' '' '' '']
 ['' '' '' '' '' '']
 ['' '' '' '' '' '']
 ['' '' '' '' '' '']
 ['o' 'x' 'e' 'n' 'y' 'y']
 ['' '' '' '' '' '']
 ['' '' '' '' '' '']]


# Other searching approaches.
We could take a candidate word (like "oxen") and make sure that all its letters are in the grid somewhere.  If not, there's no point searching for it!

But if our grid contains all the letters in our language, this will be a waste of time to compute for each candidate word.

In [44]:
letters = np.unique(grid)  # get the unique members of the grid.
letters

array(['a', 'b', 'd', 'e', 'g', 'h', 'i', 'l', 'm', 'n', 'o', 'p', 'q',
       'r', 's', 'w', 'x', 'y'], dtype='<U1')

In [45]:
np.in1d(['o','x','e','n'], letters).all()  # Are ALL the specified letters in the puzzle somewhere?

True

# What about searching diagonally? 

In [46]:
print(grid, '\n')
print(np.diagonal(grid))

[['a' 'p' 'p' 'l' 'e' 'd']
 ['n' 'n' 'i' 'g' 'a' 'l']
 ['d' 'o' 'g' 's' 'b' 'e']
 ['r' 's' 'h' 'r' 'e' 'i']
 ['o' 'x' 'e' 'n' 'y' 'y']
 ['i' 'l' 'w' 'e' 'p' 'q']
 ['d' 'r' 'e' 'h' 's' 'm']] 

['a' 'n' 'g' 'r' 'y' 'q']


In [47]:
print(np.diagonal(grid, 1))

['p' 'i' 's' 'e' 'y']


In [48]:
print(np.diagonal(grid, -1))

['n' 'o' 'h' 'n' 'p' 'm']


### So, using that technique, how do we get the other diagonals? (going from upper-right to lower-left)

In [49]:
flipped = np.fliplr(grid)  # We create a "flipped" copy of the array.
print(flipped)

[['d' 'e' 'l' 'p' 'p' 'a']
 ['l' 'a' 'g' 'i' 'n' 'n']
 ['e' 'b' 's' 'g' 'o' 'd']
 ['i' 'e' 'r' 'h' 's' 'r']
 ['y' 'y' 'n' 'e' 'x' 'o']
 ['q' 'p' 'e' 'w' 'l' 'i']
 ['m' 's' 'h' 'e' 'r' 'd']]


In [50]:
print(np.diagonal(flipped))

['d' 'a' 's' 'h' 'x' 'i']


In [51]:
%timeit flipped = np.fliplr(grid)  # We create a "flipped" copy of the array.


744 ns ± 15.1 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
